baseURL = "localhost:8080"
languageCode = "en-us"
DateForm = "12-30-2006"
title = "exdatabaseLCPQ"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
[Author]
  name = "M. Véril"
  email = "mveril@irsamc.ups-tlse.fr"
#  github = "lcpq"
   twitter = "LCPQ_UMR5626"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "channel/UC3a7Yakg9gk36G3HKDIFaYw"
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  keybase = "username"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "One dataset"
    url = "onedataset"
    weight = 2

[[menu.main]]
    name = "Multiple dataset"
    url = "multipledataset"
    weight = 3

[[menu.main]]
    name = "Papers"
    url = "papers"
    weight = 4

[[menu.main]]
    name = "About"
    url = "about"
    weight = 5

[[menu.main]]
    identifier = "external"
    name = "External links"
    weight = 6

[[menu.main]]
    parent="external"
    name = "Laboratoire de Chimie et Physique Quantique"
    url = "http://www.lcpq.ups-tlse.fr"
    weight = 6

[[menu.main]]
    parent="external"
    name = "CIESAM"
    url = "http://www.sciences.univ-nantes.fr/CEISAM"
    weight = 6

[[menu.main]]
    parent="external"
    name = "Quantum Package"
    url = "https://quantumpackage.github.io/qp2"
    weight = 6

[[menu.main]]
    parent="external"
    name = "Dalton"
    url = "https://daltonprogram.org"
    weight = 6

[[menu.main]]
    parent="external"
    name = "MRCC"
    url = "https://gaussian.com/"
    weight = 6

[[menu.main]]
    parent="external"
    name = "Gaussian"
    url = "https://gaussian.com/"
    weight = 6


[[menu.main]]
    parent="external"
    name = "EMSL Basis set"
    url = "https://www.basissetexchange.org"
    weight = 6
