baseURL = "localhost:8080"
languageCode = "en-us"
DateForm = "12-30-2006"
title = "QUEST"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
[Params]
#  homeTitle = ""
  subtitle = "QUantum Excited STates database"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[Author]
  name = "M. Véril"
  email = "mveril@irsamc.ups-tlse.fr"
#  github = "lcpq"
   twitter = "LCPQ_UMR5626"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "channel/UC3a7Yakg9gk36G3HKDIFaYw"
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  keybase = "username"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Dataset"
    url = "dataset"
    weight = 2

[[menu.main]]
    name = "Publications"
    url = "publications"
    weight = 3

[[menu.main]]
    name = "About"
    url = "about"
    weight = 4

[[menu.main]]
    identifier = "external"
    name = "External links"
    weight = 5

[[menu.main]]
    parent="external"
    name = "Laboratoire de Chimie et Physique Quantique"
    url = "http://www.lcpq.ups-tlse.fr"
    weight = 1

[[menu.main]]
    parent="external"
    name = "CIESAM"
    url = "http://www.sciences.univ-nantes.fr/CEISAM"
    weight = 2

[[menu.main]]
    parent="external"
    name = "EMSL Basis set"
    url = "https://www.basissetexchange.org"
    weight = 3

[[menu.main]]
    parent="external"
    name = "Computational Chemistry Comparison and Benchmark Database"
    url =  "https://cccbdb.nist.gov"
    weight = 4

[[menu.main]]
    parent="external"
    name = "Quantum Package"
    url = "https://quantumpackage.github.io/qp2"
    weight = 5

[[menu.main]]
    parent="external"
    name = "Dalton"
    url = "https://daltonprogram.org"
    weight = 6

[[menu.main]]
    parent="external"
    name = "MRCC"
    url = "https://gaussian.com"
    weight = 7

[[menu.main]]
    parent="external"
    name = "Gaussian"
    url = "https://gaussian.com"
    weight = 8
    