baseURL = "localhost:8080"
languageCode = "en-us"
DateForm = "12-30-2006"
title = "exdatabaseLCPQ"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
[Author]
#  name = "M. Véril"
#  email = "user@example.com"
#  github = "lcpq"
   twitter = "LCPQ_UMR5626"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "channel/UC3a7Yakg9gk36G3HKDIFaYw"
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  keybase = "username"