baseURL = "localhost:8080"
languageCode = "en-us"
DateForm = "12-30-2006"
title = "exdatabaseLCPQ"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
[Author]
#  name = "M. Véril"
#  email = "user@example.com"
#  github = "lcpq"
   twitter = "LCPQ_UMR5626"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
#  youtube = "channel/UC3a7Yakg9gk36G3HKDIFaYw"
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  keybase = "username"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "One dataset"
    url = "onedataset"
    weight = 2

[[menu.main]]
    name = "Multiple dataset"
    url = "multipledataset"
    weight = 3

#[[menu.main]]
#    name = "Papers"
#    url = "papers"
#    weight = 4

#[[menu.main]]
#    name = "About"
#    url = "about"
#    weight = 5